language: node_js
node_js:
  - "node"

script:
  - npm install
  - npm run build

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    on:
      branch: master
